compile:
	gcc -g -Wall -o program 151044046.c -lrt -lpthread
	gcc -g -Wall -o nurse nurse.c -lrt -lpthread
	gcc -g -Wall -o vaccinator vaccinator.c -lrt -lpthread
	gcc -g -Wall -o citizen citizen.c -lrt -lpthread


