compile:
	gcc -Wall -g -o myFind HW1_151044046.c

run:
	./myFind -w /home -f f2

val:
	gcc -Wall -g -o myFind HW1_151044046.c
	valgrind ./myFind -w / -b 3

test:
	gcc -Wall -g -o myFind HW1_151044046.c
	./myFind -w / -p 'rw-rw-rw-'
	#./myFind -w /home -f 'asdasdasdasdasdasdasdasd'
	#./myFind -w /home
	#./myFind -w /home -b 3
	#./myFind -w /home/yusuf/Desktop/System -t 'f'
	#./myFind -w /home -b 3 -p 'rw-rw-rw-'
	#./myFind -w /home -l 5





